### ISSUE TITLE
is it possible to set more than one user to receive moderation notices?

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#10]
at the moment we are using the config:

```
$wgModerationNotificationEnable = true;
$wgModerationNotificationNewOnly = false;
$wgModerationEmail = $wgEmergencyContact;
```

can we past an array of users, or list of emails to the system somehow?

**Comment by edwardspec** [comment]
No.
I don't plan to implement this, because this feature is needed for like 0.01% of wikis. (unless hired to do so)

Right now sending these emails is not queued (they are sent immediately when user clicks Save), so if you just add foreach() and specify 10 emails, Save would become ridiculously slow.
