### ISSUE TITLE
when do items show up in the "Spam" section

### ISSUE THREAD

**Issue by tansaku** [edwardspec/mediawiki-moderation#16]
I've marked various users as spammers, but the spam section is empty:

![](https://www.dropbox.com/s/haecu9f9u0jjcsk/Screenshot%202017-06-08%2009.44.56.png?dl=1)

**Comment by edwardspec** [comment]
If you marked some account as spammer, and this account does another edit, this edit is queued for moderation and appears in the "Spam" folder. This is called a "moderation block".

**This feature is against human spammers only**.
It makes no sense to do this with spambots, because they create new accounts each time they go spamming.
