### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by Ilovetacos135** [edwardspec/mediawiki-moderation#19]
This error popped up after running update.php.

Warning  Parameter 1 to ModerationEditHooks::onBeforePageDisplay() expected to be a reference, value given in "[Wiki Directory]/includes/Hooks.php on line 195

I already have  the 
error_reporting(E_ERROR | E_WARNING | E_PARSE);
in my LocalSettings.

**Comment by edwardspec** [comment]
This is unrelated to Moderation itself.

MediaWiki core calls `Hooks::run( 'BeforePageDisplay', [ &$this, &$sk ] );`,
while `&$this` causes warning in PHP 7.1.

This is fixed in MediaWiki core by https://phabricator.wikimedia.org/T153505
(fix will appear in MediaWiki 1.29).

**Comment by Ilovetacos135** [comment]
I know you closed this, but after your comment I went hunting. To get ride of the error I changed in

/Moderation/hooks/ModerationEditHooks.php on line 224

from 
	public static function onBeforePageDisplay( &$out, &$skin ) {
to
	public static function onBeforePageDisplay( $out, $skin ) {

**Comment by edwardspec** [comment]
You can totally use this fix in your wiki (to suppress the warning until 1.29).

I won't be applying this to the code, because:
1) &$out is correct,
2) the warning is harmless (everything works despite it),
3) this warning is already fixed in MediaWiki core (fix will appear in 1.29),
4) same warnings will be seen from hundreds of other extensions in PHP 7.1 until MediaWiki 1.29. We shouldn't edit 100 extensions for what is not even a nuisance.
