### ISSUE TITLE
[Request] Reason for Rejection

### ISSUE THREAD

**Issue by vegas23** [edwardspec/mediawiki-moderation#27]
I think adding a text field for _why_ a change was rejected would be extremely useful for feedback.

**Comment by edwardspec** [comment]
When following Good Practices (see https://www.mediawiki.org/wiki/Extension:Moderation#Recommended_use_.2F_good_practices ), the only reason why you would Reject is vandalism, spam or otherwise ill-intentioned edit. It this situation, you don't have to explain to user why you rejected his/her change.

If the edit itself is useless/incorrect but was made with good intent (e.g. badly formatted, or not interesting, or outside the scope of project - e.g. _adding excessive details into Wikipedia article about film_), it should be Approved and then reverted as usual. In this situation, reason can be specified when reverting.

**Comment by edwardspec** [comment]
Reject was designed as a one-click operation to save moderator's time.

Adding a reason field implies having a "Reject form", i.e. making it more time consuming to moderate, i.e. making the extension worse for those who follow Good Practices.
