### ISSUE TITLE
Unable to navigate back to [[Special:Moderation]] after approving/rejecting an edit

### ISSUE THREAD

**Issue by JKSH** [edwardspec/mediawiki-moderation#4]
Suppose I approve an edit. I'm taken to a URL like `index.php?title=Special:Moderation&modaction=approve&modid=55&token=008f1c9174770ba8698c4def2f769677%2B%5C`. From here, there's no link to go back to the main Moderation page.

If I click on the "Special page" link, I'm taken to the same URL, which then says _"Edit not found. Probably already approved."_ It would be nice if there was a link to take me back to `index.php?title=Special:Moderation` instead.

**Workaround**
* Always approve/reject/mark-spammer in a new browser tab, and refresh the current page afterwards
* Click "Back" after a moderation action, and refresh the page

**Possible solutions**
* Make it so that clicking "Special page" takes me to `index.php?title=Special:Moderation`
* Add a link in the wiki navigation bar

**Comment by edwardspec** [comment]
Fixed in fd48f3ec0432c76a2d51a73082f03081c3d4cd8b - link "Return to Special:Moderation" added to all actions/errors.

Though personally I prefer to click on Approve/Reject/etc. with a middle mouse button (mouse wheel), thus opening them in the tabs.

TODO (low priority): ajax handling of Approve/Reject (not leaving Special:Moderation after these links are clicked; result can be shown on Special:Moderation itself).
