### ISSUE TITLE
Suggest add a new hook 'ModerationPassed'

### ISSUE THREAD

**Issue by hyperzlib** [edwardspec/mediawiki-moderation#54]
Suggest add a new hook 'ModerationPassed' at ModerationApprovableEntry.php lines 151
it is useful to notice other extension.

**Comment by edwardspec** [comment]
Agreed, a post-approval hook will be added.

**Comment by edwardspec** [comment]
Question: does the existing PageContentSaveComplete hook cover your usecase?
For example, the following code can track approvals:

```php
public static function onPageContentSaveComplete(
    $wikiPage, $user, $content, $summary, $isMinor, $isWatch, $section, $flags,
    $revision, $status, $originalRevId, $undidRevId
) {
    if ( !$user->isAllowed( 'skip-moderation' ) ) {
        // If we are here, then the edit of $user was just Approved by moderator.
    }
}
```

Note that if the edit bypassed Moderation due to settings like `$wgModerationIgnoredInNamespaces`, then the code above would also trigger. Alternatively you can check "is the current user NOT the author of the edit?", which happens during approvals:
```php
if ( !$user->equals( RequestContext::getMain()->getUser() ) ) {
}
```

**Comment by hyperzlib** [comment]
No. I use Aliyun API to autoreview revs, so I want to send feedback to Aliyun API after revs reviewed to improve model quality.

**Comment by edwardspec** [comment]
Very well. What iinformation does the hook need to receive? Are $authorUser, $moderatorUser and $title sufficient? Or do you need things like $revid, or move-specific parameters like $oldTitle and $newTitle?

The only reason why I haven't added this hook yet is because I'm not sure about its parameters. (it has to be right, as hooks are difficult to change in the future, as to maintain backward compatibility)

I'd rather not pass ModerationApprovableEntry object to it directly, if it can be avoided. (this class can use some refactoring, and passing it to the hook would mean a promise to not change its public methods).

**Comment by hyperzlib** [comment]
the inserted ```rev_id``` and operator ```User``` object are necessary.

**Comment by edwardspec** [comment]
This can be easily obtained via `PageContentSaveComplete` hook. Here is an example:
```php
public static function onPageContentSaveComplete(
    $wikiPage, $authorUser, $content, $summary, $isMinor, $isWatch, $section, $flags,
    $revision, $status, $originalRevId, $undidRevId
) {
	$context = RequestContext::getMain();
	$contextTitle = $context->getTitle();

	if ( $contextTitle && $contextTitle->isSpecial( 'Moderation' ) ) {
		// This is approval
		$moderatorUser = $context->getUser();
		$revid = $revision->getId();

		// Do whatever you need with $moderatorUser, $revid and $authorUser
	}
}
```

**Comment by edwardspec** [comment]
Closing as unnecessary.
