### ISSUE TITLE
DeferredUpdates::doUpdates change

### ISSUE THREAD

**Issue by Krinkle** [edwardspec/mediawiki-moderation#75]
I noticed these two callers:

```lang=php
# approveAll.php
		DeferredUpdates::doUpdates( 'run' );
# ModerationApproveHookTest.php
			// Run any DeferredUpdates that may have been queued when making edits.
			// Note: PRESEND must be first, as this is where RecentChanges_save hooks are called,
			// and results of these hooks are used by ApproveHook, which is in POSTSEND.
			DeferredUpdates::doUpdates( 'run', DeferredUpdates::PRESEND );
			DeferredUpdates::doUpdates( 'run', DeferredUpdates::POSTSEND );
```

Note that `DeferredUpdates::doUpdates` is documented as internal and should not have to be called. In general, DeferredUpdates tend to run immediately or at the next DB commit when in command-line context. In any event, you can continue to use it at your own risk.

I'm letting you know that the first parameter will be removed in <https://gerrit.wikimedia.org/r/c/mediawiki/core/+/876263>.

Regarding ModerationApproveHookTest, I'd be interested in knowing whether the default stage `ALL` would work there. I believe we generally process updates in order, so perhaps this is already working correctly? Or are the updates discovered in the "wrong" order as well? If so, I would caution that this may very well be failing in your production environment as well as there are numerous contexts in which deferred updates are executed directly or together at the next DB commit (e.g. CLI maintenance scripts, and JobQueue jobs etc.). The separation only applies to web requests, and even there it is a configurable optimisation.

Perhaps you tried this already, but one solution might be to queue your update from the same hook, such that others will have been queued already.

**Comment by edwardspec** [comment]
Thank you for letting me know. This call should work fine without parameters (the separation of calls wasn't really needed in the first place). I will test this in more detail.

>  In general, DeferredUpdates tend to run immediately or at the next DB commit when in command-line context.

This test checks both cases: (1) when updates are immediate, (2) when this is disabled by setting `$wgCommandLineMode=false` (situation that happens during the user's request).

The only reason why the test calls `DeferredUpdates::run()` is because it must do some checks in "after all DeferredUpdates have completed" situation. There is no hook that would allow me to do run code at this moment, so the only option is to run DeferredUpdates explicitly, and then do the checks.

>  I would caution that this may very well be failing in your production environment

Not a concern in this case. The tested code is also covered by a blackbox test (`testApproveAllTimestamp()` in `ModerationApproveTest.php`), which doesn't rely on implementation.
