### ISSUE TITLE
Moderation Rejection Reasons Field

### ISSUE THREAD

**Issue by nymphlode** [edwardspec/mediawiki-moderation#93]
Apologies if this is the wrong place to put this, but I saw "Enhancement" tags in the closed tickets, so I'm assuming suggestions can be made here.

When rejecting edits,  it would be wonderful to have the option to provide a reason for the rejection, so that people are not confused about why their edits don't get approved.

**Comment by edwardspec** [comment]
That will not be done.

Best practices is to not reject edits that are neither vandalism nor are made with ill intent. You should approve such an edit and then revert or (if you want to specify the reason) undo it, at which point (because undo is an edit) you can specify the reason in the edit summary.

Users will not be allowed to see their rejected edits. For a vandal, this is "my glorious contributions to motivate me in the future" page.

**Comment by nymphlode** [comment]
That explains a lot, thank you!
